version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d/thetravelinghacker.conf:z
      - ./thetravelinghacker/static:/static:Z
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn thetravelinghacker.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./:/the-traveling-hacker:z
    expose:
      - "8000"
    tty: true

  db:
    image: postgres:latest
    container_name: ps01
